import os
import re

from langchain_sarvamcloud import SarvamTTS

# Map our app's language names to Sarvam language codes
LANGUAGE_MAP = {
    "English": "en-IN",
    "Hindi": "hi-IN",
    "Tamil": "ta-IN",
    "Telugu": "te-IN",
    "Kannada": "kn-IN",
    "Malayalam": "ml-IN",
    "Marathi": "mr-IN",
    "Gujarati": "gu-IN",
    "Punjabi": "pa-IN",
    "Bengali": "bn-IN",
    "Odia": "od-IN",
}

# Voices for dynamic podcast hosts
VOICE_MAP = {
    "jake": "shubh",
    "sarah": "priya",
    "host 1": "shubh",
    "host 2": "priya",
    "default": "priya",
}


def parse_podcast_script(script_text):
    """
    Parses a script generated by the LLM into speaker and text components.
    Example: 'Jake: Hello!' -> [{'speaker': 'jake', 'text': 'Hello!'}]
    """
    pattern = re.compile(r"^([\w\s]+):\s*(.*)$")
    lines = script_text.split("\n")
    dialogue = []

    current_speaker = "default"
    current_text = []

    for line in lines:
        line = line.strip()
        if not line:
            continue

        # Ignore stage directions like [Upbeat intro music]
        if line.startswith("[") and line.endswith("]"):
            continue

        # Strip markdown bold/italic asterisks just for parsing
        clean_line = line.replace("*", "")

        # Match anything up to 30 characters before a colon
        match = re.match(r"^([^:]{1,30}):\s*(.*)$", clean_line)
        if match:
            # We hit a new speaker line, save the old one
            if current_text:
                dialogue.append(
                    {"speaker": current_speaker, "text": " ".join(current_text)}
                )
            current_speaker = match.group(1).strip().lower()
            current_text = [match.group(2).strip()]
        else:
            # Continuation of the same speaker's dialogue
            if not line.startswith("[") and not line.startswith("("):
                current_text.append(line)

    if current_text:
        dialogue.append({"speaker": current_speaker, "text": " ".join(current_text)})

    return dialogue


def split_text_into_chunks(text, max_length=450):
    """
    Splits text into chunks of at most max_length characters,
    attempting to split at sentence boundaries.
    """
    chunks = []
    # Split by sentence-ending punctuation, keeping the punctuation attached
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())

    current_chunk = ""
    for sentence in sentences:
        if (
            len(current_chunk) + len(sentence) + (1 if current_chunk else 0)
            <= max_length
        ):
            if current_chunk:
                current_chunk += " " + sentence
            else:
                current_chunk = sentence
        else:
            if current_chunk:
                chunks.append(current_chunk)

            # If a single sentence is still longer than max_length, split by spaces
            if len(sentence) > max_length:
                words = sentence.split(" ")
                current_chunk = ""
                for word in words:
                    if (
                        len(current_chunk) + len(word) + (1 if current_chunk else 0)
                        <= max_length
                    ):
                        if current_chunk:
                            current_chunk += " " + word
                        else:
                            current_chunk = word
                    else:
                        if current_chunk:
                            chunks.append(current_chunk)
                        current_chunk = word
            else:
                current_chunk = sentence

    if current_chunk:
        chunks.append(current_chunk)

    return chunks


def generate_podcast_audio(script_text, language="English"):
    """
    Takes the full podcast script, parses it, and uses Sarvam AI to generate
    and yield audio chunks for each speaker sequentially.
    """
    api_key = os.getenv("SARVAM_API_KEY")
    if not api_key:
        raise ValueError(
            "SARVAM_API_KEY environment variable is not set. Please add it to your .env file."
        )

    dialogue = parse_podcast_script(script_text)
    target_language_code = LANGUAGE_MAP.get(language, "en-IN")

    import base64

    import requests

    # Dynamically assign voices based on appearance order
    # to handle translated names like "ಜೇಕ್" (Jake) in regional languages
    speaker_voices = {}

    for line in dialogue:
        speaker = line["speaker"]
        full_text = line["text"]
        if not full_text:
            continue

        if speaker not in speaker_voices:
            if len(speaker_voices) == 0:
                speaker_voices[speaker] = "shubh"  # Host 1
            else:
                speaker_voices[speaker] = "shruti"  # Host 2 / fallback

        voice_id = speaker_voices[speaker]
        chunks = split_text_into_chunks(full_text, max_length=450)

        for text_chunk in chunks:
            try:
                headers = {
                    "api-subscription-key": api_key,
                    "Content-Type": "application/json",
                }
                payload = {
                    "inputs": [text_chunk],
                    "target_language_code": target_language_code,
                    "speaker": voice_id,
                    "pace": 1.15,  # Increased pace for a more energetic podcast feel
                    "model": "bulbul:v3",
                    "output_audio_codec": "mp3",  # Directly request MP3
                }

                response = requests.post(
                    "https://api.sarvam.ai/text-to-speech",
                    headers=headers,
                    json=payload,
                )

                if response.ok:
                    data = response.json()
                    if "audios" in data and len(data["audios"]) > 0:
                        audio_bytes = base64.b64decode(data["audios"][0])
                        yield audio_bytes
                else:
                    print(f"Error from Sarvam API for {speaker}: {response.text}")

            except Exception as e:
                print(f"Error synthesizing speech for {speaker}: {e}")
                continue
