import os
import re

from sarvamai import SarvamAI

# Map our app's language names to Sarvam language codes
LANGUAGE_MAP = {
    "English": "en-IN",
    "Hindi": "hi-IN",
    "Tamil": "ta-IN",
    "Telugu": "te-IN",
    "Kannada": "kn-IN",
    "Malayalam": "ml-IN",
    "Marathi": "mr-IN",
    "Gujarati": "gu-IN",
    "Punjabi": "pa-IN",
    "Bengali": "bn-IN",
    "Odia": "od-IN",
}


def parse_podcast_script(script_text):
    """
    Parses a script generated by the LLM into speaker and text components.
    Example: 'Jake: Hello!' -> [{'speaker': 'jake', 'text': 'Hello!'}]
    """
    lines = script_text.split("\n")
    dialogue = []

    current_speaker = "default"
    current_text = []

    for line in lines:
        line = line.strip()
        if not line:
            continue

        # Ignore stage directions like [Upbeat intro music]
        if line.startswith("[") and line.endswith("]"):
            continue

        # Strip markdown bold/italic asterisks just for parsing
        clean_line = line.replace("*", "")

        # Match anything up to 30 characters before a colon
        match = re.match(r"^([^:]{1,30}):\s*(.*)$", clean_line)
        if match:
            # We hit a new speaker line, save the old one
            if current_text:
                dialogue.append(
                    {"speaker": current_speaker, "text": " ".join(current_text)}
                )
            current_speaker = match.group(1).strip().lower()
            current_text = [match.group(2).strip()]
        else:
            # Continuation of the same speaker's dialogue
            if not line.startswith("[") and not line.startswith("("):
                current_text.append(line)

    if current_text:
        dialogue.append({"speaker": current_speaker, "text": " ".join(current_text)})

    return dialogue


def split_text_into_chunks(text, max_length=450):
    """
    Splits text into chunks of at most max_length characters,
    attempting to split at sentence boundaries.
    """
    chunks = []
    # Split by sentence-ending punctuation, keeping the punctuation attached
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())

    current_chunk = ""
    for sentence in sentences:
        if (
            len(current_chunk) + len(sentence) + (1 if current_chunk else 0)
            <= max_length
        ):
            if current_chunk:
                current_chunk += " " + sentence
            else:
                current_chunk = sentence
        else:
            if current_chunk:
                chunks.append(current_chunk)

            # If a single sentence is still longer than max_length, split by spaces
            if len(sentence) > max_length:
                words = sentence.split(" ")
                current_chunk = ""
                for word in words:
                    if (
                        len(current_chunk) + len(word) + (1 if current_chunk else 0)
                        <= max_length
                    ):
                        if current_chunk:
                            current_chunk += " " + word
                        else:
                            current_chunk = word
                    else:
                        if current_chunk:
                            chunks.append(current_chunk)
                        current_chunk = word
            else:
                current_chunk = sentence

    if current_chunk:
        chunks.append(current_chunk)

    return chunks


def generate_podcast_audio(script_text, language="English"):
    """
    Takes the full podcast script, parses it, and uses Sarvam AI to generate
    and yield audio chunks for each speaker sequentially.
    """
    api_key = os.getenv("SARVAM_API_KEY")
    if not api_key:
        raise ValueError(
            "SARVAM_API_KEY environment variable is not set. Please add it to your .env file."
        )

    dialogue = parse_podcast_script(script_text)
    language_code = LANGUAGE_MAP.get(language, "en-IN")

    # Dynamically assign voices based on appearance order
    # to handle translated names like "ಜೇಕ್" (Jake) in regional languages
    speaker_voices = {}
    model = os.getenv("SARVAM_TTS_MODEL", "bulbul:v3")
    timeout = float(os.getenv("SARVAM_TTS_TIMEOUT", "60"))
    # Slower, calmer pace (1.0 = neutral) makes the podcast feel less rushed.
    pace = float(os.getenv("SARVAM_TTS_PACE", "0.95"))
    # Pitch and loudness per speaker to add natural contrast between hosts.
    voice_profile = {
        "shubh": {"pitch": -0.5, "loudness": 1.0},   # slightly lower, neutral volume
        "shruti": {"pitch": 0.4, "loudness": 1.05},  # slightly higher, a touch louder
    }
    audio_generated = False
    client = SarvamAI(api_subscription_key=api_key, timeout=timeout)

    for line in dialogue:
        speaker = line["speaker"]
        full_text = line["text"]
        if not full_text:
            continue

        if speaker not in speaker_voices:
            if len(speaker_voices) == 0:
                speaker_voices[speaker] = "shubh"  # Host 1
            else:
                speaker_voices[speaker] = "shruti"  # Host 2 / fallback

        voice_id = speaker_voices[speaker]
        profile = voice_profile.get(voice_id, {})
        chunks = split_text_into_chunks(full_text, max_length=450)

        for text_chunk in chunks:
            try:
                response = client.text_to_speech.convert(
                    text=text_chunk,
                    language_code=language_code,
                    speaker=voice_id,
                    pace=pace,
                    pitch=profile.get("pitch"),
                    loudness=profile.get("loudness"),
                    enable_preprocessing=True,
                    model=model,
                    output_audio_codec="mp3",
                )

                if response.audios:
                    import base64

                    audio_bytes = base64.b64decode(response.audios[0])
                    if audio_bytes:
                        audio_generated = True
                        yield audio_bytes

            except Exception as e:
                print(f"Error synthesizing speech for {speaker}: {e}")
                continue

    if not audio_generated:
        raise RuntimeError("Sarvam AI did not return any podcast audio.")
